apiVersion: v1
kind: Service
metadata:
  name: mcb-service
  labels:
    app: mcb
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 3001
    protocol: TCP
  selector:
    app: mcb
---
apiVersion: v1
kind: Service
metadata:
  name: mcb-loadbalancer
  labels:
    app: mcb
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3001
    protocol: TCP
  selector:
    app: mcb
